apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-orden-compra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-orden-compra
  template:
    metadata:
      labels:
        app: app-orden-compra
    spec:
      containers:
        - name: app-orden-compra
          image: eric2945/app-orden-compra
          env:
            - name: APP_CLIENTES_URL
              value: http://app-cliente-service:8080
            - name: APP_PRODUCTOS_URL
              value: http://app-producto-service:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-orden-compra
spec:
  type: ClusterIP
  selector:
    app: app-orden-compra
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080